# sam.yaml
imu:
  gravity:               9.818
  accel_noise_sigma:     0.0185    # m/s^2/√Hz
  gyro_noise_sigma:      0.00000120835   # rad/s/√Hz
  accel_bias_rw_sigma:   0.00137  # m/s^2
  gyro_bias_rw_sigma:    0.0005585 
  integration_error_cov: 1e-4
  bias_acc_omega_init:   1e-3
  sample_rate:        0.008       # dt between imu readings

sbg:
  gravity:               9.818
  accel_noise_sigma:     0.1516667
  gyro_noise_sigma:      0.067079
  accel_bias_rw_sigma:   0.014
  gyro_bias_rw_sigma:    0.08901
  integration_error_cov: 1e-4
  bias_acc_omega_init:   1e-1
  sample_rate:        0.04

extrinsics:
  imu_sensor_pose:  [0.24,  0.0,   -0.036]
  sbg_sensor_pose:  [0.46,  0.0,    0.002]
  dvl_sensor_pose:  [0.573, 0.0,   -0.063]
  gps_sensor_pose:  [0.528, 0.0,    0.071]
  baro_sensor_pose: [-0.503,0.025,  0.057]

noise_models:
  prior:
    pose_sigma:     [1e-6, 1e-6, 1e-6, 1e-6, 1e-6, 1e-6]
    velocity_sigma: [1e-3, 1e-3, 1e-3]
    bias_sigma:     [1e-3, 1e-3, 1e-3, 1e-3, 1e-3, 1e-3]

  motion_model_sigma: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  dvl_sigma:           [0.01,  0.01,  10.0]
  gps_sigma:           [0.5,   0.5,   0.5]
  barometer_sigma:     [0.01]

water_density: 998.68