# sam.yaml
imu:
  gravity:               9.818
  accel_noise_sigma:     0.000185    # m/s^2/√Hz
  gyro_noise_sigma:      0.0000520835   # rad/s/√Hz
  accel_bias_rw_sigma:   0.0000137  # m/s^2
  gyro_bias_rw_sigma:    0.0000585 
  integration_error_cov: 1e-2
  bias_acc_omega_init:   1e-2
  sample_rate:        0.008       # dt between imu readings

sbg:
  gravity:               9.818
  accel_noise_sigma:     0.001516667
  gyro_noise_sigma:      0.000067079
  accel_bias_rw_sigma:   0.0014
  gyro_bias_rw_sigma:    0.00008901
  integration_error_cov: 1e-4
  bias_acc_omega_init:   1e-4
  sample_rate:        0.04

extrinsics:
  imu_sensor_pose:  [0.24,  0.0,   -0.036]
  sbg_sensor_pose:  [0.46,  0.0,    0.002]
  dvl_sensor_pose:  [0.573, 0.0,   -0.063]
  gps_sensor_pose:  [0.528, 0.0,    0.071]
  baro_sensor_pose: [-0.503,0.025,  0.057]

noise_models:
  prior:
    pose_sigma:     [1e-12, 1e-12, 1e-12, 1e-12, 1e-12, 1e-12]
    velocity_sigma: [1e-6, 1e-6, 1e-6]
    bias_sigma:     [1e-3, 1e-3, 1e-3, 1e-3, 1e-3, 1e-3]

  motion_model_sigma: [1, 1, 1, 1,  1 , 1, 1, 1, 1]
  dvl_sigma:           [1e-5,  1e-5,  0.05]
  gps_sigma:           [0.001,   0.001,   0.001]
  barometer_sigma:     [0.001]

water_density: 998.68